/** Vite runtime companion of index.ts — keep exports in sync. */
export const ALL_TOOL_TYPES = [
    'web_fetch',
    'web_search',
    'read_file',
    'write_file',
    'shell',
    'verify',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
    'todo',
    'task_read',
    'task_update',
    'list_skills',
    'read_skill',
    'suggest_skill',
    'write_skill',
    'memory_search',
    'memory_save',
    'memory_status',
    'memory_wake',
];
/** Exact default lists from older builds — upgradeEnabledTools replaces these with ALL_TOOL_TYPES. */
export const OLD_DEFAULT_TOOLS = ['web_fetch', 'read_file', 'shell'];
export const PREV_DEFAULT_TOOLS = [
    'web_fetch',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
];
/** Prior full tool list before git_diff / create_pr / checkpoints. */
export const PREV2_DEFAULT_TOOLS = [
    'web_fetch',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
];
/** Prior full tool list before the todo checklist tool. */
export const PREV3_DEFAULT_TOOLS = [
    'web_fetch',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
];
/** Prior full tool list before skills tools. */
export const PREV4_DEFAULT_TOOLS = [
    'web_fetch',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
    'todo',
];
/** Prior full tool list before web_search. */
export const PREV5_DEFAULT_TOOLS = [
    'web_fetch',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
    'todo',
    'list_skills',
    'read_skill',
    'suggest_skill',
    'write_skill',
];
/** Prior full tool list before write_file / verify / task_read / task_update. */
export const PREV6_DEFAULT_TOOLS = [
    'web_fetch',
    'web_search',
    'read_file',
    'shell',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
    'todo',
    'list_skills',
    'read_skill',
    'suggest_skill',
    'write_skill',
];
/** Prior full tool list before MemPalace memory_* tools. */
export const PREV7_DEFAULT_TOOLS = [
    'web_fetch',
    'web_search',
    'read_file',
    'write_file',
    'shell',
    'verify',
    'grep',
    'glob',
    'git_status',
    'git_commit',
    'git_diff',
    'create_pr',
    'checkpoint_save',
    'checkpoint_restore',
    'list_dir',
    'file_outline',
    'semantic_search',
    'generate_image',
    'todo',
    'task_read',
    'task_update',
    'list_skills',
    'read_skill',
    'suggest_skill',
    'write_skill',
];
export const DEFAULT_ENABLED_TOOLS = [...ALL_TOOL_TYPES];
/** Read-only tools allowed while Plan mode is on (writes unlock after approve). */
export const PLAN_MODE_TOOLS = [
    'read_file',
    'grep',
    'glob',
    'list_dir',
    'file_outline',
    'semantic_search',
    'git_status',
    'git_diff',
    'web_fetch',
    'web_search',
    'todo',
    'task_read',
    'task_update',
    'list_skills',
    'read_skill',
    'suggest_skill',
    'memory_search',
    'memory_status',
    'memory_wake',
];
